Update attapon_docker-image.yml

diff --git a/.github/workflows/attapon_docker-image.yml b/.github/workflows/attapon_docker-image.yml
--- a/.github/workflows/attapon_docker-image.yml
+++ b/.github/workflows/attapon_docker-image.yml
@@ -25,8 +25,14 @@ jobs:
 
       - name: Run tests
         run: |
-          python -m unittest app.py | tee test_output.txt
-        continue-on-error: false
+          python -m unittest app.py > test_output.txt 2>&1
+          if grep -q "FAILED" test_output.txt; then
+            echo "Tests failed. Logging to error_log.txt."
+            cp test_output.txt error_log.txt
+            exit 1  # Markerar steget som fail
+          else
+            echo "Tests passed."
+          fi
 
   build:
     runs-on: ubuntu-latest
